version: "3.9"

services:
    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/nginx/hosts:/etc/nginx/conf.d
        links:
            - apache2
        depends_on:
            -  apache2

    apache2:
        container_name: apache2
        build:
            context: .
            dockerfile: docker/apache2/DockerFile
        volumes:
            - ./:/var/www
